name: Push main

on:
  push:
    branches:
      - main

jobs:

  release:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v3

      - name: Print secrets
        env: 
          REPO_TEST: ${{ secrets.TEST }}
          BASE64: ${{ secrets.BASE64 }}
        run: | 
          echo REPO_TEST=$REPO_TEST
          echo $REPO_TEST | rev
          echo BASE64=$BASE64
          echo $BASE64 | base64 -d | jq empty
